>  run 2413575 ics Linux 4df2092abf4e 6.6.87.2-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux  20:27:18 up 4 days, 12:54,  0 users,  load average: 1.56, 1.23, 1.18 3fef3db76bb07dd1bc29572555f77782f4b67020

diff --git a/nexus-am/am/arch/x86-nemu/img/run b/nexus-am/am/arch/x86-nemu/img/run
--- a/nexus-am/am/arch/x86-nemu/img/run
+++ b/nexus-am/am/arch/x86-nemu/img/run
@@ -1,3 +1,12 @@
 #!/bin/bash
 
-make -C $NEMU_HOME run ARGS="-l `dirname $1`/nemu-log.txt $1.bin"
+set -e
+
+# In headless environments, SDL init will block or fail unless we provide a
+# dummy video backend. Keep real windows on normal desktops by only falling
+# back when no display backend is configured.
+if [ -z "${SDL_VIDEODRIVER:-}" ] && [ -z "${DISPLAY:-}" ] && [ -z "${WAYLAND_DISPLAY:-}" ]; then
+  export SDL_VIDEODRIVER=dummy
+fi
+
+make -C "$NEMU_HOME" run ARGS="-b -l `dirname $1`/nemu-log.txt $1.bin"
